name: fe_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  http: ^0.13.6
  flutter:
    sdk: flutter
  url_launcher: ^6.2.4
  provider: ^6.1.1
  webview_flutter: ^4.0.7
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
  assets:
    - assets/images/logo.png
    - assets/images/kakao_login_medium_wide.png
